excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cpwebhosting.github.io
title: SiteGeek
tagline: Latest News, Reviews and Developments of Hosting World
description: SiteGeek.com had been working on to develop set of technologies to rate and review web hosting companies.They are currently monitoring 100 million websites for and collecting stats for the 40k hosting companies world wide with various parameters
paginate: 5